services:
  - type: web
    name: pokemon-showdown
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:minimal
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=400